#!/bin/sh

#
# chkconfig: 2345 55 25
# Description: Startup script for on Debian. Place in /etc/init.d and
#       run 'update-rc.d -f frpc defaults', or use the appropriate command
#       on your distro. For CentOS/Redhat run: 'chkconfig --add frpc'
#

### BEGIN INIT INFO
# Provides:          frpc
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: frpc service deamon
# Description:       frpc service daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/frp/frpc
DAEMON_OPTS="-c /opt/frp/frpc.ini"
NAME=frpc

set -e
. /lib/lsb/init-functions

start()
{
    log_daemon_msg "Starting $NAME" || true
    if start-stop-daemon --start --quiet --oknodo -m --pidfile /var/run/$NAME.pid -b --output /var/run/$NAME.log --exec $DAEMON -- $DAEMON_OPTS; then
        log_end_msg 0 || true
    else
        log_end_msg 1 || true
    fi
}

stop()
{
    log_daemon_msg "Stopping $NAME" || true
    if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/$NAME.pid; then
        log_end_msg 0 || true
    else
        log_end_msg 1 || true
    fi
}

status()
{
    status_of_proc -p /var/run/$NAME.pid "$DAEMON" $NAME && exit 0 || exit $?
}

case "$1" in
    start)   start ;;
    stop)    stop ;;
    status)  status ;;
    restart) stop; sleep 2; start ;;
    *)       log_action_msg "Usage: $NAME {start|stop|restart|status}" || true; exit 1 ;;
esac

exit 0

